apiVersion: 1
groups:
    - orgId: 1
      name: sit-sakura-management.jenaka.co.id
      folder: Alert
      interval: 5m
      rules:
        - uid: c69e4ca0-b1e7-47c3-afc0-407f3a313954
          title: SIT SAKURA MANAGEMENT
          condition: B
          data:
            - refId: A
              relativeTimeRange:
                from: 60
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                disableTextWrap: false
                editorMode: code
                expr: probe_http_status_code{instance=~"https://sit-sakura-management.jenaka.co.id"}
                fullMetaSearch: false
                includeNullMetadata: true
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
                useBackend: false
            - refId: B
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 200
                            - 0
                        type: gt
                      operator:
                        type: when
                      query:
                        params:
                            - A
                      reducer:
                        params: []
                        type: count
                      type: query
                    - evaluator:
                        params:
                            - 200
                            - 0
                        type: lt
                      operator:
                        type: or
                      query:
                        params:
                            - A
                      reducer:
                        params: []
                        type: count
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: ""
                intervalMs: 1000
                maxDataPoints: 43200
                refId: B
                type: classic_conditions
          noDataState: NoData
          execErrState: Error
          for: 5m
          annotations: {}
          labels: {}
          isPaused: false
