version: '3'
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      # - prometheus-data:/prometheus
    networks:
      - localprom
    ports:
      - 9090:9090
  
  node-exporter:
    image: prom/node-exporter
    networks:
      - localprom
    ports:
      - 9100:9100

  blackbox:
    image: prom/blackbox-exporter:latest
    privileged: true
    volumes:
      - ./blackbox/blackbox.yml:/etc/blackbox_exporter/config.yml
    ports:
      - '9115:9115'
    restart: unless-stopped
  
  grafana:
    image: grafana/grafana
    volumes:
      - ./provisioning:/etc/grafana/provisioning
    networks:
      - localprom
    ports:
      - 3000:3000
networks:
  localprom:
    driver: bridge